name: Review App Operator Action

description: Deploy review apps to Kubernetes using Github Actions and Review App Operator
inputs:
  review_app_name:
    description: The name of the Kubernetes Review App
    required: true
  review_app_namespace:
    description: The namespace of the Kubernetes Review App
    required: false
    default: default
  webhook_url:
    description: The target webhook URL
    required: true
  webhook_secret:
    description: The webhook secret
    required: true
  action:
    description: The action to perform, either 'deploy' or 'delete'
    required: false
    default: deploy
  image:
    description: The new Docker Image to deploy
    required: false

outputs:
  review_app_url:
    description: The URL of the review app

runs:
  using: docker
  image: Dockerfile
